name: Shell Commands  name of the workflow # name of the workflow
on: [push] # action on which workflow will be executed
jobs: # jobs ran by the workflow
  run-shell-commands: # job
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello world"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
  runs-on-windows-command:
    runs-on: windows-latest
    steps:
      - name: Directory PowerShell
        run: Get-Location